# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/vivado_projects/i2c_drive/i2c_drive.cache/wt [current_project]
set_property parent.project_path E:/vivado_projects/i2c_drive/i2c_drive.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  E:/vivado_projects/i2c_drive/i2c_drive.srcs/sources_1/new/scan_led.v
  E:/vivado_projects/i2c_drive/i2c_drive.srcs/sources_1/new/i2c_drive.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/vivado_projects/i2c_drive/i2c_drive.srcs/constrs_1/new/xdc.xdc
set_property used_in_implementation false [get_files E:/vivado_projects/i2c_drive/i2c_drive.srcs/constrs_1/new/xdc.xdc]


synth_design -top i2c_drive -part xc7a100tcsg324-1


write_checkpoint -force -noxdef i2c_drive.dcp

catch { report_utilization -file i2c_drive_utilization_synth.rpt -pb i2c_drive_utilization_synth.pb }
